 
 
 
FROM python:3.8.2-buster
 WORKDIR /app
 COPY . .
RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    curl
    
RUN apt-get update 
RUN apt-get upgrade -y

RUN apt-get install mosquitto -y
RUN apt-get install mosquitto-clients -y

   

RUN pip install paho-mqtt 
RUN pip install python-telegram-bot


 CMD ["node","python", "src/index.js", "app_Client_sensor.py", "Nodo1_temp.py", "Nodo2_lux.py", "Nodo3_humidity.py"]
